class UserConfig:
    NAME_LENGTH_MIN = 1
    NAME_LENGTH_MAX = 50
    EMAIL_LENGTH_MAX = 254
    PASSWORD_LENGTH_MIN = 8
    PASSWORD_LENGTH_MAX = 128

    DB_NAME_LENGTH_MAX = 100
    DB_EMAIL_LENGTH_MAX = 300
    DB_PASSWORD_LENGTH_MAX = 500


class ArticleConfig:
    TITLE_LENGTH_MIN = 1
    TITLE_LENGTH_MAX = 255
    URL_LENGTH_MAX = 2083

    DB_TITLE_LENGTH_MAX = 500
    DB_URL_LENGTH_MAX = 2500

class TagConfig:
    NAME_LENGTH_MIN = 1
    NAME_LENGTH_MAX = 50

    DB_NAME_LENGTH_MAX = 100

class RefreshTokenConfig:
    DB_TOKEN_LENGTH_MAX = 300