class ValidationLength:
    USER_NAME_MAX = 30
    USER_EMAIL_MAX = 254
    USER_PASSWORD_MIN = 8
    USER_PASSWORD_MAX = 72
    ARTICLE_TITLE_MAX = 255
    ARTICLE_UTL_MAX = 2083
    TAG_NAME_MAX = 30