"""init schema

Revision ID: 0926ce8c848b
Revises: 
Create Date: 2026-02-06 10:24:15.656054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0926ce8c848b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_user_created_at', 'articles', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('ix_article_user_deleted_at', 'articles', ['user_id', 'deleted_at'], unique=False, postgresql_where=sa.text('is_deleted IS true'))
    op.create_index('ix_article_user_title_lower', 'articles', ['user_id', sa.literal_column('lower(title)')], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('ix_article_user_updated_at', 'articles', ['user_id', 'updated_at'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_user_name_lower', 'tags', ['user_id', sa.literal_column('lower(name)')], unique=False)
    op.create_table('article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag')
    op.drop_index('ix_tag_user_name_lower', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_article_user_updated_at', table_name='articles', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('ix_article_user_title_lower', table_name='articles', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('ix_article_user_deleted_at', table_name='articles', postgresql_where=sa.text('is_deleted IS true'))
    op.drop_index('ix_article_user_created_at', table_name='articles', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_table('articles')
    op.drop_table('users')
    # ### end Alembic commands ###
