"""add lower on tables

Revision ID: 278ae662e4b0
Revises: 012575e55632
Create Date: 2026-01-23 10:51:09.900826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278ae662e4b0'
down_revision: Union[str, Sequence[str], None] = '012575e55632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title_lower', sa.String(length=300), nullable=False))
    op.add_column('tag', sa.Column('name_lower', sa.String(length=300), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'name_lower')
    op.drop_column('article', 'title_lower')
    # ### end Alembic commands ###
