"""fix edit

Revision ID: 335bba475d4f
Revises: 278ae662e4b0
Create Date: 2026-01-24 11:53:05.978271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '335bba475d4f'
down_revision: Union[str, Sequence[str], None] = '278ae662e4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('article', 'edited_at')
    op.alter_column('article', 'created_at', server_default=sa.text('now()'),)
    op.alter_column('article', 'is_deleted', server_default=sa.text('false'),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('article', 'updated_at')
    op.alter_column('article', 'created_at', server_default=None,)
    op.alter_column('article', 'is_deleted', server_default=None,)
    # ### end Alembic commands ###
