"""update article

Revision ID: 43b37244a53f
Revises: abb8cccbf4d3
Create Date: 2026-02-03 10:17:57.425084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b37244a53f'
down_revision: Union[str, Sequence[str], None] = 'abb8cccbf4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_deleted_article'), table_name='article', postgresql_where='(is_deleted IS TRUE)')
    op.create_index('idx_article_created_at', 'article', ['created_at'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('idx_article_deleted_at', 'article', ['deleted_at'], unique=False, postgresql_where=sa.text('is_deleted IS true'))
    op.create_index('idx_article_updated_at', 'article', ['updated_at'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_article_updated_at', table_name='article', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('idx_article_deleted_at', table_name='article', postgresql_where=sa.text('is_deleted IS true'))
    op.drop_index('idx_article_created_at', table_name='article', postgresql_where=sa.text('is_deleted IS false'))
    op.create_index(op.f('idx_deleted_article'), 'article', ['id'], unique=False, postgresql_where='(is_deleted IS TRUE)')
    # ### end Alembic commands ###
