"""upgrade database

Revision ID: 646a4fbaa40a
Revises: eca447b9a892
Create Date: 2026-02-01 23:46:23.686840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646a4fbaa40a'
down_revision: Union[str, Sequence[str], None] = 'eca447b9a892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title_lower', sa.String(length=300), sa.Computed('LOWER(title)', ), nullable=False))
    op.drop_column('article', 'normalized_title')
    op.add_column('tag', sa.Column('name_lower', sa.String(length=300), sa.Computed('LOWER(name)', ), nullable=False))
    op.drop_column('tag', 'normalized_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('normalized_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('tag', 'name_lower')
    op.add_column('article', sa.Column('normalized_title', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('article', 'title_lower')
    # ### end Alembic commands ###
