"""fix order

Revision ID: 6544bc34690a
Revises: 335bba475d4f
Create Date: 2026-01-24 12:49:12.793709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6544bc34690a'
down_revision: Union[str, Sequence[str], None] = '335bba475d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_deleted')
    op.drop_column('article', 'deleted_at')
    op.drop_column('article', 'title_lower')
    op.drop_column('article', 'updated_at')
    op.drop_column('article', 'created_at')
    op.drop_column('article', 'title')
    op.drop_column('article', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('url', sa.VARCHAR(length=2083), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('title_lower', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.add_column('article', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
