"""update article and tag

Revision ID: 86e83d2325f4
Revises: aeabd7d36119
Create Date: 2026-02-03 00:42:35.740886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e83d2325f4'
down_revision: Union[str, Sequence[str], None] = 'aeabd7d36119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_article_title_lower', 'article', [sa.literal_column('lower(title)')], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.drop_column('article', 'title_lower')
    op.create_index('idx_tag_name_lower', 'tag', [sa.literal_column('lower(name)')], unique=False)
    op.drop_column('tag', 'name_lower')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name_lower', sa.VARCHAR(length=300), sa.Computed('lower((name)::text)', persisted=True), autoincrement=False, nullable=False))
    op.drop_index('idx_tag_name_lower', table_name='tag')
    op.add_column('article', sa.Column('title_lower', sa.VARCHAR(length=300), sa.Computed('lower((title)::text)', persisted=True), autoincrement=False, nullable=False))
    op.drop_index('idx_article_title_lower', table_name='article', postgresql_where=sa.text('is_deleted IS false'))
    # ### end Alembic commands ###
