"""fix bug

Revision ID: 8d7c9d9b5c53
Revises: ffd271b13bde
Create Date: 2026-01-27 16:17:26.300002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7c9d9b5c53'
down_revision: Union[str, Sequence[str], None] = 'ffd271b13bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'title_lower')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title_lower', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
