"""add user table

Revision ID: 93117eb4153f
Revises: 43b37244a53f
Create Date: 2026-02-05 00:26:22.992439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93117eb4153f'
down_revision: Union[str, Sequence[str], None] = '43b37244a53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_article_created_at'), table_name='article', postgresql_where='(is_deleted IS FALSE)')
    op.drop_index(op.f('idx_article_deleted_at'), table_name='article', postgresql_where='(is_deleted IS TRUE)')
    op.drop_index(op.f('idx_article_title_lower'), table_name='article', postgresql_where='(is_deleted IS FALSE)')
    op.drop_index(op.f('idx_article_updated_at'), table_name='article', postgresql_where='(is_deleted IS FALSE)')
    op.create_index('ix_article_user_created_at', 'article', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('ix_article_user_deleted_at', 'article', ['user_id', 'deleted_at'], unique=False, postgresql_where=sa.text('is_deleted IS true'))
    op.create_index('ix_article_user_title_lower', 'article', ['user_id', sa.literal_column('lower(title)')], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('ix_article_user_updated_at', 'article', ['user_id', 'updated_at'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_foreign_key('article_user_id_fkey', 'article', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_tag_name_lower'), table_name='tag')
    op.create_index('ix_tag_user_name_lower', 'tag', ['user_id', sa.literal_column('lower(name)')], unique=False)
    op.create_foreign_key('tag_user_id_fkey', 'tag', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tag_user_id_fkey', 'tag', type_='foreignkey')
    op.drop_index('ix_tag_user_name_lower', table_name='tag')
    op.create_index(op.f('idx_tag_name_lower'), 'tag', [sa.literal_column('lower(name::text)')], unique=False)
    op.drop_column('tag', 'user_id')
    op.drop_constraint('article_user_id_fkey', 'article', type_='foreignkey')
    op.drop_index('ix_article_user_updated_at', table_name='article', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('ix_article_user_title_lower', table_name='article', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('ix_article_user_deleted_at', table_name='article', postgresql_where=sa.text('is_deleted IS true'))
    op.drop_index('ix_article_user_created_at', table_name='article', postgresql_where=sa.text('is_deleted IS false'))
    op.create_index(op.f('idx_article_updated_at'), 'article', ['updated_at'], unique=False, postgresql_where='(is_deleted IS FALSE)')
    op.create_index(op.f('idx_article_title_lower'), 'article', [sa.literal_column('lower(title::text)')], unique=False, postgresql_where='(is_deleted IS FALSE)')
    op.create_index(op.f('idx_article_deleted_at'), 'article', ['deleted_at'], unique=False, postgresql_where='(is_deleted IS TRUE)')
    op.create_index(op.f('idx_article_created_at'), 'article', ['created_at'], unique=False, postgresql_where='(is_deleted IS FALSE)')
    op.drop_column('article', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
