"""update article

Revision ID: abb8cccbf4d3
Revises: 86e83d2325f4
Create Date: 2026-02-03 01:23:05.291678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb8cccbf4d3'
down_revision: Union[str, Sequence[str], None] = '86e83d2325f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_deleted_article', 'article', ['id'], unique=False, postgresql_where=sa.text('is_deleted IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deleted_article', table_name='article', postgresql_where=sa.text('is_deleted IS true'))
    # ### end Alembic commands ###
