"""add delete flag and delete data on article table

Revision ID: bf5cf8f32224
Revises: d42fd69de1c4
Create Date: 2026-01-21 13:21:25.073218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5cf8f32224'
down_revision: Union[str, Sequence[str], None] = 'd42fd69de1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('article', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('article_url_key', 'article', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_url_key', 'article', type_='unique')
    op.drop_column('article', 'deleted_at')
    op.drop_column('article', 'is_deleted')
    # ### end Alembic commands ###
