"""update tag_synonym

Revision ID: cd1cbe7d83a9
Revises: 8d7c9d9b5c53
Create Date: 2026-01-27 23:34:44.330831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1cbe7d83a9'
down_revision: Union[str, Sequence[str], None] = '8d7c9d9b5c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_synonym', sa.Column('name', sa.String(length=300), nullable=False))
    op.drop_index(op.f('ix_tag_synonym_canonical_name'), table_name='tag_synonym')
    op.create_index(op.f('ix_tag_synonym_name'), 'tag_synonym', ['name'], unique=True)
    op.drop_column('tag_synonym', 'canonical_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_synonym', sa.Column('canonical_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tag_synonym_name'), table_name='tag_synonym')
    op.create_index(op.f('ix_tag_synonym_canonical_name'), 'tag_synonym', ['canonical_name'], unique=True)
    op.drop_column('tag_synonym', 'name')
    # ### end Alembic commands ###
