"""fix order

Revision ID: e92bba1bb422
Revises: 6544bc34690a
Create Date: 2026-01-24 12:49:56.875049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92bba1bb422'
down_revision: Union[str, Sequence[str], None] = '6544bc34690a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', sa.String(length=300), nullable=False))
    op.add_column('article', sa.Column('title_lower', sa.String(length=300), nullable=False))
    op.add_column('article', sa.Column('url', sa.String(length=2083), nullable=False))
    op.add_column('article', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('article', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('article', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('article', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'deleted_at')
    op.drop_column('article', 'is_deleted')
    op.drop_column('article', 'updated_at')
    op.drop_column('article', 'created_at')
    op.drop_column('article', 'url')
    op.drop_column('article', 'title_lower')
    op.drop_column('article', 'title')
    # ### end Alembic commands ###
