"""fix bug

Revision ID: fb0adcb96c87
Revises: bf5cf8f32224
Create Date: 2026-01-21 13:45:06.955868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0adcb96c87'
down_revision: Union[str, Sequence[str], None] = 'bf5cf8f32224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('article_url_key'), 'article', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('article_url_key'), 'article', ['url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
