from typing import Protocol, Type, TypeVar

T = TypeVar("T")


class UnitOfWork(Protocol):
    def __enter__(self) -> "UnitOfWork": ...

    def __exit__(self, exc_type, exc, tb) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...

    def get_repo(self, repository_type: Type[T]) -> T: ...
