"""add refresh tokens table

Revision ID: 8bceb301a094
Revises: c009253832ce
Create Date: 2026-02-10 12:41:02.311350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bceb301a094'
down_revision: Union[str, Sequence[str], None] = 'c009253832ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_cleanup', 'refresh_tokens', ['expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NOT NULL'))
    op.create_index('ix_refresh_tokens_expires', 'refresh_tokens', ['expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_refresh_tokens_expires', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_refresh_tokens_cleanup', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NOT NULL'))
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
